### ISSUE TITLE
How does this differ from wait-on?

### ISSUE THREAD

**Issue by jkomyno** [sindresorhus/wait-for-localhost#1]
Hi @sindresorhus , thanks for your commitment to open source code.
This is not a bug-related issue, only a genuine curiosity of mine, I guess.

How does this package differ from [wait-on](https://github.com/jeffbski/wait-on)?
e.g., If I wanted to wait for something in localhost on the port 3000, I could do:

- [wait-on] `$ wait-on http://localhost:3000`
- [wait-for-localhost] `$ wait-for-localhost 3000`

**Comment by sindresorhus** [comment]
I just wanted something lightweight for my specific use-case that *just works* without having any options or complexity. `wait-on` provides a lot of functionality, but that also comes at a cost, both in usage complexity and size (it's 16 MB with dependencies, while this one is 0.4 MB).
