### ISSUE TITLE
Host & Path Support

### ISSUE THREAD

**Issue by brandon93s** [sindresorhus/wait-for-localhost#10]
Hey @sindresorhus, hope you're doing well.  I'm in need of a very similar ( _super simple_ )  package, but with support for providing `host` and `path`.  My use case is for a CI pipeline to wait for a service to become healthy upon deployment by pinging a health-check endpoint.

The naming of this module locks it into `localhost`, but I wanted to surface this for consideration before creating a new module.  This module is a spread operator on the options object away from supporting hosts and paths.  

If you want to keep this focused on local development, I'll proceed with publishing the updates to `wait-for-host` and `wait-for-host-cli`.  Maybe this could consume and provide default values for localhost?

**Comment by sindresorhus** [comment]
I just wanted to keep it simple as I never needed anything other than localhost.

You probably want https://github.com/jeffbski/wait-on

**Comment by brandon93s** [comment]
Saw that, don't care for all of the dependencies.  I'll roll my own that just exposes a subset of the built-in [node options](https://nodejs.org/api/http.html#http_http_request_options_callback) object to keep it simple!
