### ISSUE TITLE
npm not in sync with master

### ISSUE THREAD

**Issue by indieisaconcept** [sindresorhus/wait-for-localhost#13]
Hi @sindresorhus,

I noticed version `3.2.0` on npm doesn't reflect current master which includes `options.path`. Are there any plans to push an update?

Thanks

**Comment by sindresorhus** [comment]
I just forgot.

https://github.com/sindresorhus/wait-for-localhost/releases/tag/v3.3.0

**Comment by indieisaconcept** [comment]
Thanks!
