### ISSUE TITLE
API mode

### ISSUE THREAD

**Issue by simonhaenisch** [sindresorhus/wait-for-localhost#3]
Hi, would you be willing to add (or accept a PR for) an API mode? Basically just return a promise that resolves once the server is available (I want to use this in a CLI tool).

```js
const waitForLocalhost = require('wait-for-localhost');

(async () => {
  await waitForLocalhost({ port });

  // ready to do some stuff, e. g. access served files
})();
```

Edit: whoops, just saw that someone already submitted PR #2 for that 🙈

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/wait-for-localhost/pull/2
